### ISSUE TITLE
Could not find soffice binary

### ISSUE THREAD

**Issue by SushKenyNeosoft** [elwerene/libreoffice-convert#16]
I'm trying to convert a buffer of .jpg file to pdf using libreoffice-convert in Windows 10.

I'm getting this error:

`stack:"Error: Could not find soffice binary\n    at D:\Projects\eVisa\Workspace\Source Code\Microservices\Back Office\node_modules\libreoffice-convert\index.js:33:41\n    at D:\Projects\eVisa\Workspace\Source Code\Microservices\Back Office\node_modules\libreoffice-convert\node_modules\async\dist\async.js:3377:9\n    at D:\Projects\eVisa\Workspace\Source Code\Microservices\Back Office\node_modules\libreoffice-convert\node_modules\async\dist\async.js:473:16\n    at iteratorCallback (D:\Projects\eVisa\Workspace\Source Code\Microservices\Back Office\node_modules\libreoffice-convert\node_modules\async\dist\async.js:1064:13)\n    at D:\Projects\eVisa\Workspace\Source Code\Microservices\Back Office\node_modules\libreoffice-convert\node_modules\async\dist\async.js:969:16\n    at D:\Projects\eVisa\Workspace\Source Code\Microservices\Back Office\node_modules\libreoffice-convert\node_modules\async\dist\async.js:3369:13\n    at D:\Projects\eVisa\Workspace\Source Code\Microservices\Back Office\node_modules\libreoffice-convert\index.js...`

I've just installed the library and my Node.js version is 12.x.

**Comment by elwerene** [comment]
Where did you install Libre Office? 

Am 18. Februar 2020 06:20:26 MEZ schrieb SushKenyNeosoft <notifications@github.com>:
>I'm trying to convert a buffer of .jpg file to pdf using
>libreoffice-convert in Windows 10.
>
>I'm getting this error:
>
>`stack:"Error: Could not find soffice binary\n    at
>D:\Projects\eVisa\Workspace\Source Code\Microservices\Back
>Office\node_modules\libreoffice-convert\index.js:33:41\n    at
>D:\Projects\eVisa\Workspace\Source Code\Microservices\Back
>Office\node_modules\libreoffice-convert\node_modules\async\dist\async.js:3377:9\n
>at D:\Projects\eVisa\Workspace\Source Code\Microservices\Back
>Office\node_modules\libreoffice-convert\node_modules\async\dist\async.js:473:16\n
>at iteratorCallback (D:\Projects\eVisa\Workspace\Source
>Code\Microservices\Back
>Office\node_modules\libreoffice-convert\node_modules\async\dist\async.js:1064:13)\n
>at D:\Projects\eVisa\Workspace\Source Code\Microservices\Back
>Office\node_modules\libreoffice-convert\node_modules\async\dist\async.js:969:16\n
>at D:\Projects\eVisa\Workspace\Source Code\Microservices\Back
>Office\node_modules\libreoffice-convert\node_modules\async\dist\async.js:3369:13\n
>at D:\Projects\eVisa\Workspace\Source Code\Microservices\Back
>Office\node_modules\libreoffice-convert\index.js...`
>
>I've just installed the library and my Node.js version is 12.x.

**Comment by SushKenyNeosoft** [comment]
Do I need to install Libre Office in windows too?

**Comment by elwerene** [comment]
yes! 

Am 18. Februar 2020 10:44:13 MEZ schrieb SushKenyNeosoft <notifications@github.com>:
>Do I need to install Libre Office in windows too?

**Comment by SushKenyNeosoft** [comment]
> yes! Am 18. Februar 2020 10:44:13 MEZ schrieb SushKenyNeosoft <notifications@github.com>:
> […](#)
> Do I need to install Libre Office in windows too?

Ok Sir, Thanks!

**Comment by muhammadrohan3** [comment]
> 

What if I have to deploy my code on heroku

**Comment by averrows** [comment]
Me too. Any answer for this?

**Comment by JorgeSilvaVM** [comment]
> Me too. Any answer for this?

You have to install libreoffice in your machine, because libreoffice-convert use the program installed

**Comment by manusiakemos** [comment]
i install libreoffice on docker but it show me error
Could not find soffice binary

**Comment by manusiakemos** [comment]
<img width="679" alt="image" src="https://github.com/elwerene/libreoffice-convert/assets/31971611/20ec3cf2-c240-40a6-ae1d-677e1922e232">

```yaml
version: "3.9"
services:
  mysql:
    build:
      context: "./docker/mysql"
      dockerfile: "Dockerfile"
      args:
        - MYSQL_VERSION=${MYSQL_VERSION}
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${WORKSPACE_TIMEZONE}
    ports:
      - '3306:3306'
    volumes:
      - ./data/db:/var/lib/mysql
    networks:
      - backend
      - frontend
  node:
    working_dir: /home/node/app
    build:
      context: .
      dockerfile: "Dockerfile"
    restart: no
    environment:
      DB_SCHEMA: mysql
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_USER}
      DB_HOST: mysql
    depends_on:
      - mysql
    ports:
      - ${WORKSPACE_PORT}:8000
    stdin_open: true
    tty: true
    volumes:
      - .:/home/node/app
      - ./node_modules:/home/node/app/node_modules
    networks:
      - backend
      - frontend
  libreoffice:
    image: lscr.io/linuxserver/libreoffice:latest
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - CUSTOM_USER=username
      - PASSWORD=password
    volumes:
      - ./data/libreoffice/config:/config
    ports:
      - 3000:3000
      - 3001:3001
    restart: unless-stopped
networks:
  frontend:
  backend:
```
